spring:
  cloud:
    consul:
      discovery:
        port: 9095
        enabled: true
        health-check-path: /actuator/health
        instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
        service-name: auth-api-gateway
      config:
        watch:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-application
          uri: lb://user-application
          predicates:
            - Path=/api/users/**
            - Path=/api/roles/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10    # requests per second
                redis-rate-limiter.burstCapacity: 20    # max burst
                key-resolver: "#{@userJwtKeyResolver}"
        - id: patientapplication
          uri: lb://patientapplication
          predicates:
            - Path=/api/patients/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10    # requests per second
                redis-rate-limiter.burstCapacity: 20    # max burst
                key-resolver: "#{@userJwtKeyResolver}"
        - id: patientvitalapplication
          uri: lb://patientvitalapplication
          predicates:
            - Path=/api/vital-signs/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10    # requests per second
                redis-rate-limiter.burstCapacity: 20    # max burst
                key-resolver: "#{@userJwtKeyResolver}"
        - id: patientvitalmetricsapplication
          uri: lb://patientvitalmetricsapplication
          predicates:
            - Path=/api/audit-logs/**
            - Path=/api/patient-search/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10    # requests per second
                redis-rate-limiter.burstCapacity: 20    # max burst
                key-resolver: "#{@userJwtKeyResolver}"

jhipster:
  clientApp:
    name: 'authApiGatewayApp'

server:
  address: 0.0.0.0
  port: 9095

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-application/v3/api-docs
      - name: patient-service
        url: /patientapplication/v3/api-docs
      - name: patient-vitals-service
        url: /patientvitalapplication/v3/api-docs
      - name: patient-metrics-service
        url: /patientvitalmetricsapplication/v3/api-docs

keycloak:
  realm: ${keycloak.realm}
  client-id: ${keycloak.clientId}
  client-secret: ${keycloak.clientSecret}
  token-uri: ${keycloak.tokenUri}


