spring:
  elasticsearch:
    uris: http://elasticsearch:9200
  data:
    elasticsearch:
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://vitals_user:vitals_pass@mongo:27017/vitals
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        hostname: host.docker.internal
        ip-address: host.docker.internal
        tags:
          - profile=${spring.profiles.active}
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}
      host: consul
      port: 8500
  cache:
    type: redis
    redis:
      host: redis
      port: 6379
      timeout: 60000
      password: ${redis.password}
  rabbitmq:
    host: rabbitmq         # Docker service name
    port: 5672
    username: guest         # or your actual user
    password: guest         # or your actual password
    listener:
      simple:
        retry:
          enabled: true

rabbitmq:
  queue:
    patient: patient-info-queue

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.ideas2it.training.patient: DEBUG
    org.springframework.data.elasticsearch: DEBUG