spring:
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        tags:
          - profile=${spring.profiles.active}
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}
      host: consul
      port: 8500

  data:
    mongodb:
      uri: mongodb://vitals_user:vitals_pass@mongo:27017/vitals
    elasticsearch:
      uris: http://elasticsearch:9200
      repositories:
        enabled: true

  cache:
    type: redis
    redis:
      host: reds
      port: 6379
      timeout: 60000
      password: ${redis.password}

rabbitmq:
  queue:
    patient: patient-info-queue

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.ideas2it.training.patient: DEBUG

