spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        tags:
          - profile=${spring.profiles.active}
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}
      host: localhost
      port: 8500

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/patientRecords
    username: ${spring.datasource.username}
    password: ${spring.datasource.username}
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      password: ${redis.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"

client-url:
  user-module: http://sample:9090/api/auth
  patient-module: http://patientapplication:9090/api/auth

logging:
  level:
    root: INFO
    com.ideas2it.training.patient: DEBUG

