spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${jwt.issuerUri}

  jpa:
    open-in-view: false # Disables the "Open Session in View" pattern, which keeps the Hibernate session open during the view rendering phase. Setting it to false improves performance and avoids lazy-loading issues.
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.timezone.default_storage: NORMALIZE
      hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true # Ensures that Hibernate does not rely on auto-commit behavior for database connections.
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  liquibase:
    enabled: true
    contexts: dev

  cloud:
    consul:
      discovery:
        port: 9090
        enabled: true
        service-name: user-application
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      config:
        watch:
          enabled: false

server:
  address: 0.0.0.0
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info

jhipster:
  clientApp:
    name: 'Jhipster-Microservice'
    
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  override-with-generic-response: false
  show-actuator: true
  cache:
    disabled: true
  paths-to-match: /**
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true

  # 👇 This ensures generated OpenAPI points to gateway, not Docker IP
  servers:
    - url: http://localhost:9095/user-application


